### ISSUE TITLE
Off topic question - rails game

### ISSUE THREAD

**Issue by david-loffredo** [plutoscarab/Arafel#1]
Apologies for the off topic issue, but seems to be the only way to message you on github.

Was just wondering if you ever considered publishing the source to your rails game.    I still play it quite regularly and very much enjoy it but it has a few UI things that would be nice to smooth out.

Cheers, Dave

**Comment by plutoscarab** [comment]
Oh wow, that’s awesome. I have to figure out which old hard drive it’s on. Crossing fingers
________________________________
From: David Loffredo ***@***.***>
Sent: Tuesday, October 25, 2022 6:42:45 AM
To: plutoscarab/Arafel ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [plutoscarab/Arafel] Off topic question - rails game (Issue #1)


Apologies for the off topic issue, but seems to be the only way to message you on github.

Was just wondering if you ever considered publishing the source to your rails game. I still play it quite regularly and very much enjoy it but it has a few UI things that would be nice to smooth out.

Cheers, Dave

**Comment by plutoscarab** [comment]
I found five copies of the source, and my version control fu was poor back then. I can put them all up in different branches if you’re willing to figure out what’s what
________________________________

**Comment by david-loffredo** [comment]
LOL!   Go for it.   I frequently deal with code that goes back 35+ years, when SCCS was cutting edge.   I should be able to sort it out :-)

**Comment by plutoscarab** [comment]
Added a repository called Rails with empty main branch and five option branches. Good code is probably one of the first three.
